### ISSUE TITLE
update forms

### ISSUE THREAD

**Issue by feav** [infotel-iss/notesBackend#11]
## To fill a form that deals with OneToMany relations entities.
**Example : PARCOURS**.  To add one parcours, we have to know the  **DEPARTEMENT**, **NIVEAU** and **OPTION** we want to join to him.
We may use **label** to help users.
![](https://lh4.googleusercontent.com/72pANgM3OTJ1n1PZJ4mwBkQKLInht1RYdchW8iBir9ORNzrtpea_JV9GZldBdwRW4TJ8eDtFTmYR6zBnxBJX=w1366-h647-rw) 
@douwevincent

**Comment by royken** [comment]
@feav la version actuelle du projet ne le fait pas déjà ?

**Comment by douwevincent** [comment]
@feav Il nous faut plus d'information. Comme le dit @royken , j'ai l'impression que cette fonctionnalité est implémentée et marche bien
