### ISSUE TITLE
Adding functionality to generate an end of study report

### ISSUE THREAD

**Issue by douwevincent** [infotel-iss/notesBackend#2]
At the end of every cycle, there is a need to generate a report for all students registered for the current year. 
Some students didn't register for all "niveaux" associated to a cycle. Therefore, a special treatment is provided for them.
Examples of this kind of report are attached.

[diplomation 1.pdf](https://github.com/infotel-iss/notesBackend/files/745764/diplomation.1.pdf)
[diplomation 2.pdf](https://github.com/infotel-iss/notesBackend/files/745765/diplomation.2.pdf)

**Comment by douwevincent** [comment]
A basic implementation is done but it quite slow

**Comment by royken** [comment]
Let me have a look at it :-)

**Comment by royken** [comment]
Having some issues here... may be due to database
![request](https://user-images.githubusercontent.com/7059358/33443705-8319f8e4-d5f8-11e7-9d2d-cae687670484.png)
![result](https://user-images.githubusercontent.com/7059358/33443726-9324d4d4-d5f8-11e7-85b4-f85c737d65f5.png)

**Comment by douwevincent** [comment]
@royken You need to update your database and you need to set the attribute TERMINAL to true for every level (niveau) where students are supposed to get a degree (I think it should be Licence 3 and Master 2).
Just a thought; maybe we need to add database migrations to the project.
