### ISSUE TITLE
Merge the frontend and the backend

### ISSUE THREAD

**Issue by douwevincent** [infotel-iss/notesBackend#4]
Currently, we have two separate projects: the frontend and the backend. In the world of micro-services, this is probably a good thing but I would prefer to deal only with a single project.
It is then required the merge the frontend and the backend. Remove everything related to primefaces (since we didn't update this part very much to match the changes in the services) and leave only the only with AngularJS.

**Comment by royken** [comment]
I think this is what we are doing, we have a frontend project with angularJs and a backend which only exposes some resources as restful web services. The primefaces part is not really used.

**Comment by royken** [comment]
@douwevincent it is done. I've merger the angularjs and backend project. In order to have it work, you will modify all the api path in the frontend project ( I did the merge the lazy way). In every module, replace /api/cours (for example) by /noteBackend/api/cours, as /noteBackend is my backend context.

**Comment by royken** [comment]
@douwevincent, @yayaousman made me realize that modals does not open with the merged project. I also noticed that even in the web server (apache) modals does not open also. It only opens when we call in virtual server

**Comment by yayaousman** [comment]
@royken So we have to find other versatile deployment solutions that will make the project work in as much context as possible

**Comment by royken** [comment]
@yayaousman I think you can handle this issue
