### ISSUE TITLE
gestionnotes

### ISSUE THREAD

**Issue by yayaousman** [infotel-iss/notesBackend#6]
je vais comprendre le projet

**Comment by royken** [comment]
Bonjour Yaya,
Ce projet intitulé notesBackend fait partie du projet de l'application de gestion de notes de l'ISS.

**Comment by yayaousman** [comment]
justement l'application fonctionne correctement et sert meme deja à traiter les notes , l'idée est de mettre un systeme d'authentification pour deployer l'application sur un reseau. c'est un peu la raison de mon travail. mais je te dis que j'ai des grosses difficultés à faire fonctionner l'application sur mon ordi

**Comment by yayaousman** [comment]
Donc je voudrais comprendre comment le faire
Qu'est ce que tu peut me proposer de faire.

**Comment by royken** [comment]
Donc si je comprends bien ton soucis majeure est le déploiement de la solution?
Alors merci de répondre à ces question:

- C'est quoi ton environnement de travail ?

- As-tu réussi à cloner le projet et à l'intégrer dans ton environnement de travail ?

- As-tu déjà tavailler avec les outils suivants: Mysql, apache, Glassfish, Netbeans ?

**Comment by yayaousman** [comment]
environnement java
j'ai reussi à cloner le projet
mais je ne travaille pas sur glassfish je travaille avec tomcat

**Comment by yayaousman** [comment]
Stp, je t'attend

**Comment by royken** [comment]
Alors tu devras migrer sur Glassfish (ou wildfly, voire JBoss bien que j'ai pas encore testé dessus).
Je suppose que tu travaille avec Maven associé à un IDE. En rappel c'est un projet Netbeans.
Après avoir cloné le projet, tu l'ouvres avec Netbeans (ou ton IDE préféré) et tu exécutes les opérations de > _**clean and build**_ sur le projet pour résoudre les problèmes de dépendance. Tu dois être connecté à ton repository maven pour exécuter cette opération. Pour faire simple une connexion internet suffit.
Une fois ces opérations achevées nous passerons à la phase de déploiement proprement dite.
Note: ceci ne concerne que le projet noteBackend. Pour ce qui du projet client, tu devras créer un issue dans ledit projet

**Comment by yayaousman** [comment]
ok j'ai reussi à l'ouvrir mais je parviens pas à me connecter à la base de données

**Comment by royken** [comment]
Tu peux aussi faire  > _**mvn clean package**_  dans ta console maven en et place du > _**clean and build**_  de ton IDE si tu es fan du _> pourquoi faire facil quand on peut faire compliqué?

_

**Comment by yayaousman** [comment]
est ce pas possible d'utiliser Tomcat à la place de glassfish

**Comment by royken** [comment]
#  Connexion à la base de données
Glassish utilise les **_sources de données_** (_data source_) pour se connecter à la base de données.
Une datasource a deux paramètres, un _**pool de connexion**_ (JDBC Connection Pool) qui a les infos de connexion à la BD et un nom de JNDI (Java Naming and Directory Interface) qui est lié au serveur.
  ## Création d'une data source
Pour Créer une datasource, il faut avant toute chose démarrer glassfish.
1) Soit tu te diriges vers le dossier d'installation _$Glassfish_Home/bin_ et tu tapes la commande : **_asadmin start-domain domain1_**
2) Soit tu pars dans la section _Service -> Servers_ de Netbeans, tu fait un click droit sur Glassfish Server et tu click sur _Start_
Une fois glassfish démarrée, tu ouvres la fenêtre d'administration en te dirigeant sur l'URL **_localhost:4848_** depuis ton navigateur favoris. tu auras la page suivante
![admin](https://user-images.githubusercontent.com/7059358/29628978-319ff7b4-882f-11e7-8f1c-b1e5a7dbb78c.png)
Dans le menu latéral gauche tu cliques sur **_Resources -> JDBC_**
![jdbc](https://user-images.githubusercontent.com/7059358/29629118-9bd41f0c-882f-11e7-817a-2bc2be3cdab8.png)
### Création d'un pool de données
Pour créer un pool de données tu cliques sur **JDBC Connection Pools**
![pool](https://user-images.githubusercontent.com/7059358/29629197-db9ca6e0-882f-11e7-8dd7-e973a5e50236.png)
Une fois sur la page qui liste les pool de données disponibles sur ta machine, tu cliques sur **New** et tu remplis les doonées.
![pool1](https://user-images.githubusercontent.com/7059358/29629268-27ab3e98-8830-11e7-82a4-85dff28d2f02.png)
La figure ci-dessus illustre le step 1
Dans le step 2, les données importantes sont:
- user: _(nom utilisateur Base de données)_ **root** chez moi
- password: _(mot de passe de l'utilisateur BD)_ **admin** chez moi
- port: _(port de la BD)_ 3306 puisque c'est MySQL
- Url: _(URL de connexion à la BD)_  **jdbc:mysql://localhost:3306/notes**
- URL: (même valeu)
- DatabaseName: _(nom de la base de données)_ **notes** chez moi
et tu enregistres
### Création du nom JDNI
Tu reviens sur la page Resources -> JDBC et tu cliques sur **JDBC Resources**
![jndi](https://user-images.githubusercontent.com/7059358/29629662-9264c898-8831-11e7-9995-ceec42f8e951.png)
Tu as liste des noms et les pool de connexion associés.
Pour en créer un, tu cliques sur **New**
Tu renseigne le nom, et tu chosis le nom de la pool (celle créée précédemment).
Pour te faciliter la tâche, je te conseille de mettre comme nom de JNDI _**jdbc/notesDatasource**_ ainsi tu ne devras rien modifier dans le code.
Tu enregistres et c'est tout !

**Comment by royken** [comment]
Quant à savoir si on ne peut pas migrer sur Tomcat, je répondrais simplement en disant que ceci est une application JEE, donc utilises uniquement les technologies JEE. L'une de ces technologies utilisée sont les EJB (v3.1). **Apache Tomcat ne supporte pas les EJB !!!!** Cependant, une version d'Apache supporte les EJB, Apache Tomcat + JEE = **Apache TomEE**. J'ai personnellement jamais essayé.
Sieur @douwevincent avez-vous déjà essayé TomEE ?

**Comment by yayaousman** [comment]
cool je vais essayé et je tiens informé

**Comment by yayaousman** [comment]
voila le message que je recois quand j"essai de demarrer glassfih
could not start glassfish server 4.1.1 http or htpps listined port is occupied while server is runnig

**Comment by royken** [comment]
Ceci veut dire qu'un des deux pour 8080 (listener1 utilisé pour le http) et 8181 (listener2 utilisé pour le https) est en cours d'utilisation. Etant donné que tu es fan de Tomcat, je miserais sur le 8080 qui est en cours d'utilisation par celui-ci.
Ce que tu peux faire c'est stopper Tomcat.
Pour connaitre le service utilisant un port tu peuc taper la commande : **_sudo netstat -lpn |grep :8080_** (environnement linux).
Toutefois, je te conseillerais d'utiliser Glassfish 4.1, étant donné qu'il y a énormement de bugs lors de la création de sources de données sur la version 4.1.1

**Comment by yayaousman** [comment]
/home/usmansy/Images/Screenshot from 2017-08-24 10:29:40.png

**Comment by yayaousman** [comment]
![screenshot from 2017-08-24 10 29 40](https://user-images.githubusercontent.com/28540205/29661696-c33daef4-88bc-11e7-9bc5-a0204040b148.png)

**Comment by royken** [comment]
You must upload your screenshoot, not just copy and past. You can do that either by drag and drop, or click on "selecting them"

**Comment by yayaousman** [comment]
je vous decrit les differentes etapes
![screenshot from 2017-08-24 11 11 19](https://user-images.githubusercontent.com/28540205/29661798-04e78384-88bd-11e7-8719-a849af01badf.png)
suivra
![screenshot from 2017-08-24 11 15 56](https://user-images.githubusercontent.com/28540205/29662014-c4e5544a-88bd-11e7-86dd-18f84b92af8d.png)
Et en fin
![screenshot from 2017-08-24 11 16 13](https://user-images.githubusercontent.com/28540205/29662035-d1e7a40e-88bd-11e7-9023-49309309d066.png)

**Comment by yayaousman** [comment]
j'arrive seulement jusqu'ici lorsque j'utilise la 4.1.1

**Comment by royken** [comment]
Je me souviens avoir dit que la 4.1.1 avait des bugs.

**Comment by yayaousman** [comment]
Dès que j'execute l'application, je tombe sur la page d'authentification que je viens de definir:
![screenshot from 2017-08-26 09 29 53](https://user-images.githubusercontent.com/28540205/29739888-3ec262e2-8a41-11e7-9c65-befc287aa40a.png)
Je saisi les parametres de connection, et voila ce que j'optiens
![screenshot from 2017-08-26 09 24 37](https://user-images.githubusercontent.com/28540205/29739883-10aa3d26-8a41-11e7-8aef-c67a88932dd1.png)
Et dès lors je ne parviens plus à derouler les menus.

**Comment by yayaousman** [comment]
Dès que j'execute l'application, je tombe sur la page d'authentification que je viens de definir:
![screenshot from 2017-08-26 09 29 53](https://user-images.githubusercontent.com/28540205/29739888-3ec262e2-8a41-11e7-9c65-befc287aa40a.png)
Je saisi les parametres de connection, et voila ce que j'optiens
![screenshot from 2017-08-26 09 24 37](https://user-images.githubusercontent.com/28540205/29739883-10aa3d26-8a41-11e7-8aef-c67a88932dd1.png)
Et dès lors je ne parviens plus à derouler les menus.

**Comment by royken** [comment]
1) En programmation on se sert des logs. Je suis pas sorcier pour connaître ce qui se passe en background de ton application. Le navigateur que tu utilises (Chrome) a une console. 
2) Tu as déployé le front-end comment ?

**Comment by yayaousman** [comment]
Voila l'erreur que j'obtiens
![screenshot from 2017-08-28 13 41 08](https://user-images.githubusercontent.com/28540205/29773745-a4e04114-8bf6-11e7-988c-0eb00e2c269e.png)

**Comment by royken** [comment]
Où est l'erreur?

**Comment by yayaousman** [comment]
voila ce que j'obtiens
![screenshot from 2017-08-28 15 25 19](https://user-images.githubusercontent.com/28540205/29777809-33c6c7aa-8c05-11e7-8bba-68e0e126e6ed.png)

**Comment by yayaousman** [comment]
et la suite
![screenshot from 2017-08-28 15 26 41](https://user-images.githubusercontent.com/28540205/29777856-5d139188-8c05-11e7-9f35-818b887fe5a7.png)

**Comment by yayaousman** [comment]
donc aucune posibilité de me connecter à la base des données

**Comment by royken** [comment]
L'url de l'api c'est avec notes et non notesBackend (qui est le nom du projet)

**Comment by yayaousman** [comment]
Voila ce que j'obtiens quand je renomme le dossier
![screenshot from 2017-08-28 18 03 11](https://user-images.githubusercontent.com/28540205/29784266-4a5f7c08-8c1b-11e7-8070-3ffab4705e6d.png)

**Comment by yayaousman** [comment]
J'ai changé tous les notesBackend par notes, j'ai aussi renommer le dossier notesBackend 
mais lorsque j'execute voila ce que j'obtiens: 
GET http://localhost:8080/notesBackend/api/cycles 404 (Not Found)

**Comment by yayaousman** [comment]
or il nya plus de trace de notes backend dans le fichier pourtant

**Comment by yayaousman** [comment]
Tres occupé j'imagine...

**Comment by royken** [comment]
Même avec notesBackend j'ai le bon résultat:
![niveaux](https://user-images.githubusercontent.com/7059358/29859742-71e8d364-8d5b-11e7-9399-9ac82eca1d44.png)

**Comment by yayaousman** [comment]
je vois, c'est cool mais malheureusement pas chez moi.

**Comment by douwevincent** [comment]
Bonjour,
@yayaousman  je pense les étapes fournies par @royken devrait normalement te permettre de déployer correctement l'application.
Ces différents échanges ont démontré qu'il est necessaire d'écrire un fichier README qui détaille comment déployer l'application dans un environnement de production. Je crois qu'il s'agira de récopier une partie des instructions fournies lors de ces échanges.

**Comment by yayaousman** [comment]
Merci, deploiement reussi! mais autre soucis. lorsque j'essai d'effectuer un enregistrement j'ai ce probleme:
![screenshot from 2017-08-31 15 32 23](https://user-images.githubusercontent.com/28540205/29928960-2908a70c-8e62-11e7-8ac8-71d93b6a176f.png)
